local entity_id = GetUpdatedEntityID()
EntityAddTag(entity_id,"boss")
EntityAddTag(entity_id,"touchmagic_immunity")
EntityAddTag(entity_id,"weaken_NOT")
EntityAddTag(entity_id,"no_swap")
EntityAddTag(entity_id,"glue_NOT")
EntityAddTag(entity_id,"curse_NOT")
--EntityAddTag(entity_id,"yoMamaJoke_immunity")